url: https://https://fastidious-beijinho-e792c6.netlify.app # replace with your webring's URL, which should end in .netlify.app (no slash afterwards)
include: [_redirects]
github_repo_url: https://github.com/leoromance/moshtest # replace with your repository's URL, which should begin with https://github.com/ and should also have no slash at the end
